# Generated by Django 4.2.3 on 2023-09-10 06:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweet_app', '0003_retweet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Retweet',
            new_name='RetweetModel',
        ),
    ]
